# Generated by Django 4.2 on 2023-04-09 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_profile_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='like',
            field=models.ManyToManyField(related_name='liketwitt', to=settings.AUTH_USER_MODEL),
        ),
    ]
